name: simple gradle build github action

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 24
#      uses: actions/setup-java@v4
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: '24'
        distribution: 'graalvm'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3

    - name: Change wrapper permissions
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Test with Gradle
      run: ./gradlew test