name: simple gradle build github action

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'zulu'
        architecture: x64
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Change wrapper permissions
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Test with Gradle
      run: ./gradlew test